---
- name: Install zsh (with dependencies)
  apt:
    name={{ item }}
    state=present
    update_cache=yes
  with_items: "{{ dependencies }}"
  become: true
  when: ansible_os_family == "Debian"

- name: Install zsh (with dependencies)
  homebrew:
    name={{ item }}
    state=present
    update_homebrew=yes
  with_items: dependencies
  when: ansible_os_family == "Darwin"

- name: Install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
  become_user: "{{ansible_ssh_user}}"

- name: Back up existing ~/.zshrc
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc ~/.zshrc.bak ; fi
  become_user: "{{ansible_ssh_user}}"

- name: Back up existing ~/.zsh_aliases
  shell: if [ -f ~/.zsh_aliases ]; then mv ~/.zsh_aliases ~/.zsh_aliases.bak ; fi
  become_user: "{{ansible_ssh_user}}"

- name: Copy my .zshrc
  get_url: url={{ zsh_gist_url }} dest=~/.zshrc
  become_user: "{{ansible_ssh_user}}"

- name: Copy my .zsh_aliases 
  get_url: url={{ zsh_aliases_gist_url }} dest=~/.zsh_aliases
  become_user: "{{ansible_ssh_user}}"

- name: Get zsh path
  command: which zsh 
  register: zsh_path

- name: Switch to zsh
  user: name={{ansible_ssh_user}} shell={{ zsh_path.stdout }}
  become: true
